# Generated by Django 2.1 on 2020-08-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyAPI', '0003_userintent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=500)),
                ('college', models.CharField(max_length=500)),
                ('campus', models.CharField(max_length=500)),
            ],
        ),
    ]
