# Generated by Django 2.1 on 2020-08-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyAPI', '0004_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='college_acronym',
            field=models.CharField(default='unavailable', max_length=100),
        ),
    ]
