# Generated by Django 2.1 on 2020-09-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyAPI', '0009_auto_20200902_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='name',
            field=models.CharField(default='No event name', max_length=500),
        ),
    ]
