# Generated by Django 2.1 on 2020-09-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyAPI', '0010_calendar_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='color',
            field=models.CharField(default='#004980', max_length=100),
        ),
    ]
