# Generated by Django 2.1 on 2020-11-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyAPI', '0011_calendar_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='random',
            name='question',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='random',
            name='answer',
            field=models.CharField(max_length=2000),
        ),
    ]
