# Generated by Django 2.1 on 2020-11-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyAPI', '0012_auto_20201112_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=150)),
                ('message', models.CharField(default='', max_length=150)),
                ('is_disable', models.BooleanField(default=False, max_length=150)),
            ],
        ),
    ]
