# Generated by Django 2.1 on 2020-11-23 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyAPI', '0014_auto_20201121_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_name', models.CharField(max_length=1000)),
                ('email', models.EmailField(blank=True, max_length=5000)),
                ('facebook', models.URLField(blank=True, max_length=2000)),
                ('landline', models.CharField(blank=True, max_length=500)),
                ('college_secretary', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
