# Generated by Django 2.1 on 2020-11-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyAPI', '0015_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ref',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
