# Generated by Django 2.1 on 2021-02-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyAPI', '0016_contact_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1000)),
                ('accuracy', models.IntegerField()),
            ],
        ),
    ]
