# Generated by Django 2.1 on 2021-02-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinyAPI', '0018_auto_20210210_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betatest',
            name='accuracy',
            field=models.CharField(max_length=100),
        ),
    ]
